---
# tasks file for mindx.nfs.server
#
- name: install nfs server
  shell: |
      dpkg --force-all -i {{ client_deb }}/*.deb
      dpkg --force-all -i {{ server_deb }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when: OS_ID == 'ubuntu'

- name: create nfs path
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  with_items: "{{ nfs_exports }}"

- name: config nfs /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{item}} *(rw,sync,no_root_squash)"
    state: present
  with_items: "{{ nfs_exports }}"

- name: "restart nfs"
  systemd:
    name: "nfs-server"
    enabled: true
    state: restarted
