apiVersion: v1
kind: ConfigMap
metadata:
  name: reset-config-mindx-infer-test     # The value of JobName must be the same as the name attribute of the following job. The prefix reset-config- cannot be modified.
  namespace: vcjob                      # Select a proper namespace based on the site requirements. (The namespaces of ConfigMap and Job must be the same. In addition, if the tjm component of MindX-add exists, the vcjob namespace cannot be used.)
data:
  reset.json: |
    {
      "status":"initializing"
    }
  checkCode: ""
---

apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: mindx-infer-test
  namespace: vcjob                      # Select a proper namespace based on the site requirements.
  labels:
    ring-controller.atlas: ascend-910b
    fault-scheduling: "force"
spec:
  minAvailable: 1                       # The value of minAvailable is 1 in a single-node scenario, only set as 1 when infer task
  schedulerName: volcano                # Use the Volcano scheduler to schedule jobs.
  policies:
    - event: PodEvicted
      action: RestartJob
  maxRetry: 3
  queue: default
  tasks:
  - name: "default-test"
    replicas: 1                         # The value of replicas is 1 in a single-node scenario, only set as 1 when infer task
    template:
      metadata:
        labels:
          app: infer
          ring-controller.atlas: ascend-910b
      spec:
        containers:
          - image: infer_image:latest             # Inference image, which can be modified.
            imagePullPolicy: IfNotPresent
            name: infer
            env:
            # ASCEND_VISIBLE_DEVICES env variable is used by ascend-docker-runtime when in the whole card scheduling scene with volcano scheduler. please delete it when in the static or dynamic vNPU scheduling scene or without volcano.
            - name: ASCEND_VISIBLE_DEVICES
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['huawei.com/Ascend910']               # The value must be the same as resources.requests.
            command: ["/bin/bash", "-c", "./infer.sh"]
            resources:
              requests:
                huawei.com/Ascend910: 1          # Number of required NPUs. The maximum value is 2. You can add lines below to configure resources such as memory and CPU.
              limits:
                huawei.com/Ascend910: 1          # The value must be consistent with that in requests.
            volumeMounts:
              - name: localtime                  # The container time must be the same as the host time.
                mountPath: /etc/localtime
              - name: fault-config
                mountPath: /user/restore/fault/config
              - name: reset-config
                mountPath: /user/restore/reset/config
        nodeSelector:
          host-arch: huawei-arm                  # Configure the label based on the actual job.
          accelerator-type: card-910b-infer      # servers (with Atlas 300I A2 cards)
        volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: reset-config
          configMap:
            name: reset-config-mindx-infer-test                  # Correspond to the ConfigMap name above.
        restartPolicy: OnFailure