- debug:
    msg: "******************************Login in to  harbor******************************"

- name: create certificate directory
  file:
    path: "/etc/docker/certs.d/{{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}}/"
    state: directory
    mode: 700

- name: copy harbor certs
  copy:
    src: "/etc/docker/certs.d/{{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}}/ca.crt"
    dest: "/etc/docker/certs.d/{{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}}/"
    mode: "0750"
    remote_src: no

- name: docker login harbor
  shell: "docker login {{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}} -u admin -p {{ HARBOR_PASSWORD }}"
  register: login_result

- name: message
  debug:
    msg: "{{ login_result.stdout }}"
