{
 "title": "集群状态",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "集群CPU和内存",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "cpu总核数(个)" },
    {
     "expr": "sum(container_spec_cpu_quota / 100000)",
     "legendFormat": "cpu 使用"
    },
    {
     "expr": "sum(machine_memory_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "内存总大小(Gb)"
    },
    {
     "expr": "sum(container_memory_usage_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "内存使用"
    }
   ]
  },
  {
   "title": "集群节点数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "legendFormat": "集群总节点数"
    },
    { "expr": "count(kubelet_node_name)", "legendFormat": "集群可用节点数" }
   ]
  },
  {
   "title": "节点状态",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "集群NPU数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(machine_npu_nums)", "legendFormat": "集群总NPU数量" },
    {
     "expr": "sum(machine_npu_nums)-count(npu_container_info)",
     "legendFormat": "空闲NPU数量"
    }
   ]
  },
  {
   "title": "各节点NPU数量",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 13 },
   "targets": [
    { "expr": "machine_npu_nums", "legendFormat": "{{job}}" },
    {
     "expr": "count(npu_container_info) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}