{
 "title": "节点状态",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "节点",
    "query": {
     "query": "label_values(kubelet_node_name, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$hostname 节点cpu使用率%",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$hostname\"}[1m])) * 100",
     "legendFormat": "CPU使用率"
    }
   ]
  },
  {
   "title": "$hostname 节点内存使用率%",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "repeat": "hostname",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{instance=~\"$hostname\"} / node_memory_MemTotal_bytes{instance=~\"$hostname\"}) * 100",
     "legendFormat": "内存使用率"
    }
   ]
  },
  {
   "title": "$hostname 节点网络实时接收/发送字节(Kb/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{instance=~\"$hostname\", device!~\"tap.*|veth.*|br.*|docker.*|virbr.*|lo*|cali.*|tunl.*|.*vnic\"}[5m])/1024*8)",
     "legendFormat": "接收"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{instance=~\"$hostname\", device!~\"tap.*|veth.*|br.*|docker.*|virbr.*|lo*|cali.*|tunl.*|.*vnic\"}[5m])/1024*8)",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "$hostname 磁盘使用率%",
   "type": "gauge",
   "description": "root：指root用户\nnon-root：指非root用户",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$hostname\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$hostname\"}) * 100",
     "legendFormat": "root: {{mountpoint}}"
    },
    {
     "expr": "(1 - node_filesystem_avail_bytes{fstype=~\"xfs|ext4\",instance=~\"$hostname\"} / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$hostname\"}) * 100",
     "legendFormat": "non-root: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "$hostname 磁盘IOPS(iops)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_reads_completed_total{instance=~\"$hostname\"}[1m])) + sum by (instance) (irate(node_disk_writes_completed_total{instance=~\"$hostname\"}[1m]))",
     "legendFormat": "IPOS"
    }
   ]
  }
 ]
}