- name: check user exist
  shell: getent passwd HwHiAiUser | wc -l
  register: user_info

- name: check uid and gid exists
  shell: getent passwd | awk -F ':' '{print $3,$4}' | grep -c 1000
  register: id_info

- name: create user
  shell: |
    groupadd HwHiAiUser
    useradd -g 1000 -d /home/HwHiAiUser -m HwHiAiUser -s /bin/bash
  when: "'0' in user_info.stdout and '0' in id_info.stdout"

- name: message
  debug:
    msg:
      - "can not find user HwHiAiUser, please create user first"
      - "for example:"
      - "create group: groupadd HwHiAiUser"
      - "create  user: useradd -g HwHiAiUser -d /home/HwHiAiUser -m HwHiAiUser -s /bin/bash"
      - "set password: passwd HwHiAiUser"
  failed_when: true
  when: user_info.stdout == '0' and id_info.stdout != '0'

- name: check user group
  getent:
    database: group
    key: HwHiAiUser
    fail_key: no
  register: group_info

- name: message
  debug:
    msg:
      - "user HwHiAiUser not in group HwHiAiUser, please check!"
  failed_when: true
  when: "'HwHiAiUser' not in group_info.ansible_facts.getent_group"
