---
# distribute resources
- hosts:
    - master
    - worker
    - nfs_server
  roles:
    - role: mindx.resource
      vars:
        base_dir: "{{ playbook_dir }}"

# install softwares
- hosts:
    - master
    - worker
  roles:
    - role: mindx.docker
    - role: mindx.k8s.install
    - role: mindx.nfs.client

# master init k8s
- hosts: master
  roles:
    - role: mindx.k8s.master

# worker join k8s
- hosts: worker
  roles:
    - role: mindx.k8s.worker

# config nfs server
- hosts: nfs_server
  roles:
    - role: mindx.nfs.server
      vars:
        nfs_exports:
          - /data/platform
          - /data/user

# mysql
- hosts: mysql
  roles:
    - role: mindx.k8s.label
      vars:
        label_key: mysql
        label_value: master
    - role: mindx.mysql
      vars:
        capacity: 20Gi
        data_path: /data/mysql

# install harbor
- hosts:
    - master
  roles:
    - role: mindx.harbor
