# defaults file for ascend.mysql
state: "present"
resource_dir: "~/resources"
OS_ID: "{{ lookup('ini', 'ID type=properties section=global file=/etc/os-release') }}"
OS_VERSION_ID: "{{ lookup('ini', 'VERSION_ID type=properties section=global file=/etc/os-release') | replace('\"', '') }}"

image_dir: "{{resource_dir}}/images/{{ansible_architecture}}"
mysql_data_path: "/data/atlas_mysql"
k8s_namespace: "mindx-dl"
