- name: create base package directory not rpm
  file:
    path: "{{ unzip_dir }}"
    state: directory
    mode: 0750
  when:
    - not use_rpm_command
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

# 复制unzip软件包到远端并解压
- name: unarchive unzip software on remote
  ansible.builtin.unarchive:
    src: "{{ unzip_dir }}/{{ ansible_architecture }}.tar.gz"
    dest: "{{ unzip_dir }}"
    mode: 0750
    remote_src: no
  when:
    - not use_rpm_command
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

- name: install unzip - not rpm
  shell: dpkg --force-all -i {{ unzip_dir }}/{{ ansible_architecture }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - not use_rpm_command
    - inventory_hostname != "localhost"
  ignore_errors: true

- name: create base package directory - rpm
  file:
    path: "{{ libselinux_dir }}"
    state: directory
    mode: 0750
  when:
    - use_rpm_command
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

# 复制libselinux软件包到远端并解压
- name: unarchive libselinux software on remote
  ansible.builtin.unarchive:
    src: "{{ libselinux_dir }}/{{ ansible_architecture }}.tar.gz"
    dest: "{{ libselinux_dir }}"
    mode: 0750
    remote_src: no
  when:
    - use_rpm_command
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

- name: install libselinux openEuler
  shell: rpm -iUv {{ libselinux_dir }}/{{ ansible_architecture }}/*.rpm --nodeps --force
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - use_rpm_command
    - inventory_hostname != "localhost"
  ignore_errors: true