- name: include vars
  include_vars: ../defaults/main.yml

- name: check if the driver is installed
  shell: "npu-smi info"
  register: shell_run_result
  ignore_errors: True
  when:
    - inventory_hostname in groups['worker']

- name: if driver is not installed, set unique variables
  delegate_to: localhost
  delegate_facts: true
  set_fact:
    is_driver_installed: "false"
  when:
    - inventory_hostname in groups['worker']
    - shell_run_result.rc != 0

- name: check driver failed
  fail:
    msg: "please check that all worker nodes have the driver installed."
  when:
    - hostvars['localhost']['is_driver_installed'] is defined and hostvars['localhost']['is_driver_installed'] == false

# 复制unzip包到ubuntu上
- name: copy unzip package to remote
  copy:
    src: "{{ unzip_dir }}/"
    dest: "{{ unzip_dir }}/"
  when:
    - os_name|lower == 'ubuntu'
    - os_version == '18.04'
    - inventory_hostname != "localhost"


- name: install unzip - ubuntu
  shell: dpkg --force-all -i {{ unzip_dir }}/*.deb
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - os_name|lower == 'ubuntu'
    - os_version == '18.04'
    - inventory_hostname != "localhost"
  ignore_errors: true

# 压缩libselinux软件包
- name: archive libselinux software on localhost
  local_action:
    module: archive
    path: "{{ base_dir }}/{{ os_package_name }}/{{ item }}"
    dest: "{{ base_dir }}/{{ os_package_name }}/{{ item }}.tar.gz"
    mode: 0640
  loop:
    - aarch64
    - x86_64
  when:
    - inventory_hostname == "localhost"
    - os_package_name == 'OpenEuler_20.03_LTS'
    - no_copy_flag != "true"
  run_once: true

- name: create base package directory
  file:
    path: "{{ base_dir }}/{{ os_package_name }}"
    state: directory
    mode: 0750
  when:
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

# 复制libselinux软件包到远端并解压
- name: unarchive libselinux software on remote
  ansible.builtin.unarchive:
    src: "{{ base_dir }}/{{ os_package_name }}/{{ ansible_architecture }}.tar.gz"
    dest: "{{ base_dir }}/{{ os_package_name }}"
    mode: 0750
    remote_src: no
  when:
    - os_package_name == 'OpenEuler_20.03_LTS'
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

- name: install libselinux openEuler
  shell: rpm -iUv {{ base_dir }}/{{ os_package_name }}/{{ ansible_architecture }}/libselinux/*.rpm --nodeps --force
  environment:
    DEBIAN_FRONTEND: noninteractive
    DEBIAN_PRIORITY: critical
  when:
    - os_package_name == 'OpenEuler_20.03_LTS'
    - inventory_hostname != "localhost"
  ignore_errors: true