# 创建K8s镜像目录
- name: create k8s image directory
  file:
    path: "{{ k8s_image_dir }}"
    state: directory
    mode: 0750
  when:
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

# 复制k8s镜像包到远端并解压
- name: unarchive k8s base images on remote
  ansible.builtin.unarchive:
    src: "{{ k8s_image_dir }}/{{ ansible_architecture }}.tar.gz"
    dest: "{{ k8s_image_dir }}"
    mode: 0750
    remote_src: no
  when:
    - inventory_hostname != "localhost"
    - not (host_count == "1" and first_host == "localhost")
    - no_copy_flag != "true"

# 只加载基础镜像，如果有多master，kube-vip镜像在其他步骤执行
- name: load k8s images on master
  shell: "docker load -i {{ item }}"
  with_fileglob:
    - "{{ k8s_image_dir }}/{{ ansible_architecture }}/calico*.tar.gz"
    - "{{ k8s_image_dir }}/{{ ansible_architecture }}/kube*.tar.gz"
    - "{{ k8s_image_dir }}/{{ ansible_architecture }}/coredns*.tar.gz"
    - "{{ k8s_image_dir }}/{{ ansible_architecture }}/etcd*.tar.gz"
    - "{{ k8s_image_dir }}/{{ ansible_architecture }}/pause*.tar.gz"