apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 20Gi
  hostPath:
    path: {{ mysql_data_path }}
