# defaults file for mindx.k8s.prom
state: 'present'
PROM_YAML_DIR: "~/deploy_yamls/prometheus"
HARBOR_URL: "{{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}}/"
REPO_URL: "{{ HARBOR_URL if HARBOR_HOSTNAME != '' else '' }}"
PROM_NAMESPACE: "{{ K8S_NAMESPACE }}"
