- debug:
    msg: "******************************check resources******************************"

- name: copy roles to resources
  local_action:
    module: copy
    src: "{{ base_dir }}/playbooks/roles"
    dest: "{{ resource_dir }}"
    remote_src: yes
  changed_when: false

- name: check if resource tar exist
  local_action: stat path=~/resources.tar.gz
  register: resource_tar
  when:
    - not (host_count == "1" and first_host == "localhost")

- name: archive
  local_action:
    module: archive
    path: "{{ resource_dir }}"
    dest: ~/resources.tar.gz
  when:
    - not (host_count == "1" and first_host == "localhost")
    - not resource_tar.stat.exists

- name: clean resources
  file:
    state: absent
    path: ~/resources
  when:
    - ansible_connection == "local"

- name: local host link
  file:
    src: "{{ resource_dir }}"
    dest: ~/resources
    state: link
  when: ansible_connection == "local"

- name: copy to resources remote hosts
  copy:
    src: ~/resources.tar.gz
    dest: ~/
  when:
    - ansible_connection != "local"
    - no_copy_flag != "true"

- name: clean remote resources
  file:
    state: absent
    path: ~/resources
  when:
    - ansible_connection != "local"
    - no_copy_flag != "true"

- name: uncompress on remote
  ansible.builtin.unarchive:
    src: ~/resources.tar.gz
    dest: ~/
    remote_src: yes
  when:
    - ansible_connection != "local"
    - no_copy_flag != "true"
