- debug:
    msg: "******************************check resources******************************"

- name: check if resource tar exist
  local_action: stat path=~/resources.tar.gz
  register: resource_tar
  when:
    - not (host_count == "1" and first_host == "localhost")

- name: archive
  local_action:
    module: archive
    path: "{{ resource_dir }}"
    dest: ~/resources.tar.gz
    mode: 0640
  when:
    - not (host_count == "1" and first_host == "localhost")
    - not resource_tar.stat.exists

- name: copy to roles remote hosts
  copy:
    src: ~/.ansible/roles
    dest: ~/.ansible/
    mode: 0750
  when:
    - ansible_connection != "local"
    - no_copy_flag != "true"

- name: copy to resources remote hosts
  copy:
    src: ~/resources.tar.gz
    dest: ~/
    mode: 0640
  when:
    - ansible_connection != "local"
    - no_copy_flag != "true"

- name: clean remote resources
  file:
    state: absent
    path: ~/resources
  when:
    - ansible_connection != "local"
    - no_copy_flag != "true"

- name: uncompress on remote
  ansible.builtin.unarchive:
    src: ~/resources.tar.gz
    dest: ~/
    mode: 0750
    remote_src: yes
  when:
    - ansible_connection != "local"
    - no_copy_flag != "true"
