---
- hosts:
    - master
    - master_backup
    - worker
  tasks:
    - name: include vars
      include_vars: os_map.yaml

    - name: get OS ID
      shell: grep -oP "^ID=\"?\K\w+" /etc/os-release
      changed_when: false
      register: os_id

    - name: get OS VERSION
      shell: grep -oP "^VERSION_ID=\"?\K\w+\.?\w*" /etc/os-release
      changed_when: false
      register: os_ver

    - name: set os_name
      set_fact:
        os_name: "{{ os_dict[os_id.stdout] }}"
        cacheable: yes
      when: os_id.stdout in os_dict

    - name: set os_version first
      set_fact:
        os_version: "{{ os_ver.stdout }}"
        cacheable: yes

    - name: set os_version second
      set_fact:
        os_version: "{{ os_version_dict[os_id.stdout][os_ver.stdout] }}"
        cacheable: yes
      when: os_id.stdout in os_version_dict


- hosts: localhost
  tasks:
    - name: set facts_cache dir permission
      shell: chmod -R 640 /etc/ansible/facts-cache/*
      failed_when: false
