---
# distribute resources
- hosts:
    - master
    - worker
    - master_backup
  roles:
    - role: mindx.resource
      vars:
        resource_list:
          - linux_aarch64
          - linux_x86_64
          - ubuntu_18.04_aarch64
          - ubuntu_18.04_x86_64
          - centos_7.6_aarch64
          - centos_7.6_x86_64
        support_os:
          - CentOS
          - Ubuntu
