---
# install docker
- hosts:
    - localhost
    - master
    - worker
  gather_facts: false
  vars_files:
    - roles/mindx.docker/vars/main.yml
  tasks:
    - include_tasks: roles/mindx.docker/tasks/main.yml

- hosts:
    - master
    - worker
  gather_facts: false
  vars_files:
    - roles/mindx.docker/vars/main.yml
  tasks:
    - include_tasks: roles/mindx.docker/tasks/install.yml
      when:
        - not docker_installed
