# 创建harbor的证书目录
- name: create docker cert dir
  file:
    path: "/etc/docker/certs.d/{{ HARBOR_SERVER }}"
    state: directory
    recurse: true
    mode: 0755

- name: create docker cert dir
  copy:
    src: "{{ item }}"
    dest: "/etc/docker/certs.d/{{ HARBOR_SERVER }}/"
    mode: 0600
    owner: "root"
    group: "root"
    loop:
      - "{{ HARBOR_CA_FILE }}"
      - "{{ HARBOR_KEY_FILE }}"
      - "{{ HARBOR_CRT_FILE }}"
    when:
      - inventory_hostname != "localhost"