- name: message
  debug:
    msg: "*************************start set harbor config***************************"

- name: login harbor use http
  include_tasks: http.yml
  when: harbor_use_http

- name: login harbor use https
  include_tasks: https.yml
  when: not harbor_use_http

# 配置完登录harbor的方式之后，重启docker
# 安装完docker之后不用重启，这里会重启
- name: "restart docker"
  systemd:
    name: "docker"
    enabled: true
    state: restarted

- name: login to harbor
  shell: "docker login {{ HARBOR_SERVER }} --username={{ HARBOR_ADMIN_USER }} --password={{ HARBOR_ADMIN_PASSWORD }} 2>/dev/null | grep 'Login Succeeded' | wc -l"
  register: login_msg
  no_log: true

- name: faild to login
  fail:
    msg: "login harbor failed, please check"
  when: login_msg.stdout == "0"