- name: message
  debug:
    msg: "**********start install MindX DL********************"

- name: check namespace
  shell: "kubectl get namespace | awk '$1 ~ /^volcano-system$/ {print $1}'"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  changed_when: false
  register: get_namespace

- name: create namespace
  shell: "kubectl create namespace volcano-system"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  when: get_namespace.stdout != "volcano-system"

- name: create image-pull-secret
  shell: |
    kubectl delete secret --namespace={{ item }} image-pull-secret
    kubectl create secret docker-registry image-pull-secret \
    --namespace={{ item }} \
    --docker-server={{ HARBOR_IP }}:{{ HARBOR_HTTPS_PORT }} --docker-username=admin --docker-password={{ HARBOR_PASSWORD }}
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  loop:
    - default
    - kube-system
    - mindx-dl
    - volcano-system

- name: copy dlinstall script
  copy:
    src: "{{role_path}}/files/dlinstall"
    dest: /usr/bin/
    mode: 0700

- name: install MinX DL
  shell: "/usr/bin/dlinstall --harbor {{ HARBOR_IP }} --harbor-port {{ HARBOR_HTTPS_PORT }} --nfs {{ NFS_IP }} {{ item }}"
  ignore_errors: true
  when: "ansible_architecture in item"
  with_fileglob:
    - "{{ resource_dir }}/mindxdl/*.zip"
