- name: message
  debug:
    msg: "******************************start join k8s on master_backup******************************"

- name: message
  debug:
    msg: "master_backup can not contain master in inventory_file, please check"
  failed_when: true
  when:
    - "'master_backup' in groups"
    - item == groups['master'][0]
  loop: "{{ groups['master_backup'] }}"

- name: check k8s
  shell: "kubectl cluster-info 2>&1 | grep 'is running at' | wc -l"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  register: cluster_info

- name: message
  debug:
    msg: "k8s is running already, please check"
  failed_when: true
  when: cluster_info.stdout != "0"

- name: get token
  shell: kubeadm token create --print-join-command
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: token_cmd

- name: get certificate-key
  shell: kubeadm init phase upload-certs --upload-certs
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: cert_cmd

- name: load k8s images on master
  shell: "docker load -i {{ item }}"
  with_fileglob:
    - "{{ k8s_image }}/calico*.tar.gz"
    - "{{ k8s_image }}/kube*.tar.gz"
    - "{{ k8s_image }}/coredns*.tar.gz"
    - "{{ k8s_image }}/etcd*.tar.gz"
    - "{{ k8s_image }}/pause*.tar.gz"

- name: join cluster
  shell: "{{ token_cmd.stdout }} --control-plane --certificate-key {{ cert_cmd.stdout.split('key:\n')[-1] }} --node-name={{NODE_NAME}}"
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""

- name: create kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: 0750

- name: set cluster config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    mode: "0640"
    remote_src: yes

- name: taint nodes
  shell: kubectl taint nodes {{NODE_NAME}} node-role.kubernetes.io/master-
  environment:
    http_proxy: ""
    https_proxy: ""
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
