- name: message
  debug:
    msg: "*************************start install docker***************************"

- name: check docker service
  shell: systemctl is-active docker
  register: docker_status
  changed_when: false
  ignore_errors: true

- include_tasks: install.yml
  when: docker_status.stdout != "active"
