- name: message
  debug:
    msg: "**********************start push images to harbor***********************"

- include: create_project.yml PROJECT_NAME="{{item}}"
  with_items:
    - mindx
    - k8s.gcr.io
    - dockerhub
    - prom
    - grafana
    - mysql
    - openresty
    - calico
    - volcanosh

- include: push.yml image="{{item}}"
  with_fileglob:
    - "{{ resource_dir }}/images/*.tar.gz"
