- debug:
    msg: "******************************start install harbor******************************"

- name: install docker-compose
  copy:
    src: "{{ resource_dir }}/linux_{{ ansible_architecture }}/docker-compose"
    dest: "/usr/bin/docker-compose"
    mode: "0750"
    remote_src: yes

- name: check harbor service
  shell: docker-compose ls | grep harbor | grep running | wc -l
  register: harbor_service

- name: install harbor
  include_tasks: install.yml
  when: harbor_service.stdout == "0"

- name: create certificate directory on controller
  local_action:
    module: file
    path: "/etc/docker/certs.d/{{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}}/"
    state: directory
    mode: 700

- name: copy harbor certs from remote to controller
  ansible.builtin.fetch:
    src: "/etc/docker/certs.d/{{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}}/ca.crt"
    dest: "/etc/docker/certs.d/{{HARBOR_HOSTNAME}}:{{HARBOR_HTTPS_PORT}}/"
    flat: yes

- name: message
  debug:
    msg: "harbor is running"
  when: harbor_service.stdout == "1"
