- debug:
    msg: "start install k8s"

- name: disable swap
  shell: swapoff -a

- name: set swap in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '.*?swap.*?'

- include_tasks: ubuntu_18.04.yml
  when:
    - OS_ID == 'ubuntu'
    - OS_VERSION_ID == '18.04'

- include_tasks: common.yml

- name: load k8s images
  shell: docker load -i {{item}}
  with_fileglob:
    - "{{image_dir}}/kube*.tar"
    - "{{image_dir}}/pause*.tar"
    - "{{image_dir}}/etcd*.tar"
    - "{{image_dir}}/coredns*.tar"
  when: online == false

- name: load calico images
  shell: docker load -i {{item}}
  with_fileglob:
    - "{{image_dir}}/calico*.tar"
  when: online == false

- name: "restart kubelet"
  systemd:
    name: "kubelet"
    enabled: true
    state: restarted
