apiVersion: v1
kind: Service
metadata:
  name: license-manager-svc
  namespace: mindx-dl
  labels:
    run: license-manager-svc
spec:
  type: ClusterIP
  ports:
    - name: default
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: license-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-manager
  namespace: mindx-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-manager
  template:
    metadata:
      labels:
        app: license-manager
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      nodeSelector:
        masterselector: dls-master-node
      automountServiceAccountToken: false
      containers:
        - name: license-manager
          ports:
            - name: default
              containerPort: 8081
              protocol: TCP
          image: license-manager:v3.0.RC2
          resources:
            requests:
              memory: 1300Mi
              cpu: 1000m
            limits:
              memory: 1300Mi
              cpu: 1000m
          imagePullPolicy: Never
          command: ["/bin/bash", "-c", "--"]
          args: ["/mindx-dl/license-manager -ip=0.0.0.0 -port=8081"]
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
              add: ["DAC_OVERRIDE","SETUID","SETGID","AUDIT_WRITE"]
            runAsUser: 9000
            runAsGroup: 9000
          volumeMounts:
            - name: log-license-manager
              mountPath: /var/log/mindx-dl/license-manager
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: keystore-kmc
              mountPath: /etc/mindx-dl/kmc_primary_store
            - name: keystore-kmcfg
              mountPath: /etc/mindx-dl/.config
            - name: keystore-license
              mountPath: /etc/mindx-dl/license-manager
      volumes:
        - name: log-license-manager
          hostPath:
            path: /var/log/mindx-dl/license-manager
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: keystore-kmc
          hostPath:
            path: /etc/mindx-dl/kmc_primary_store
        - name: keystore-kmcfg
          hostPath:
            path: /etc/mindx-dl/.config
        - name: keystore-license
          hostPath:
            path: /etc/mindx-dl/license-manager
