# defaults file for ascend.docker
resource_dir: "~/resources"
HARBOR_HTTP_PORT: 7080
HARBOR_HTTPS_PORT: 7443
HARBOR_PATH: "/data/harbor"
HARBOR_CERT: "/data/cert/harbor.crt"
HARBOR_KEY: "/data/cert/harbor.key"
PROJECT_NAME: "mindx"
