---
# install harbor
- hosts:
    - harbor
  roles:
    - role: mindx.harbor.install

- hosts:
    - master
    - worker
    - localhost
  roles:
    - role: mindx.harbor.login

- hosts: localhost
  roles:
    - role: mindx.harbor.push
