---
# master init k8s
- hosts: master
  roles:
    - role: mindx.k8s.master
    - role: mindx.k8s.label
      vars:
        label_key: masterselector
        label_value: dls-master-node
    - role: mindx.k8s.prom
    - role: mindx.k8s.autolabel
    - role: mindx.kubeedge

# worker join k8s
- hosts: worker
  roles:
    - role: mindx.k8s.worker
    - role: mindx.k8s.label
      vars:
        label_key: node-role.kubernetes.io/worker
        label_value: worker
        delegate_to_master: "true"
    - role: mindx.k8s.autolabel
