---
# mysql
- hosts: mysql
  roles:
    - role: mindx.k8s.label
      vars:
        label_key: mysql
        label_value: master
    - role: mindx.mysql
      vars:
        capacity: 20Gi
        data_path: "{{MYSQL_DATAPATH}}"
