FROM ubuntu:18.04
RUN useradd -d /home/hwMindX -u 9000 -m -s /usr/sbin/nologin hwMindX &&\
    usermod root -s /usr/sbin/nologin
COPY ./npu-exporter  /usr/local/bin/
COPY ./lib  /usr/local/lib
COPY ./run_for_310P_1usoc.sh /
RUN chown root:root /usr/local/bin/npu-exporter  &&\
    chmod 750 -R /home/hwMindX &&\
    chmod 500 /run_for_310P_1usoc.sh &&\
    chmod 550 /usr/local/bin/ /usr/local/lib &&\
    chmod 500 /usr/local/lib/* &&\
    chmod 500 /usr/local/bin/npu-exporter &&\
    echo 'umask 027' >> /etc/profile && \
    echo 'source /etc/profile' >> ~/.bashrc
