apiVersion: v1
kind: ConfigMap
metadata:
  name: fault-config-default-test-mindspore     # The value of JobName must be the same as the name attribute of the following job. The prefix fault-config- cannot be modified.
  namespace: default                      # Select a proper namespace based on the site requirements. (The namespaces of ConfigMap and Job must be the same. In addition, if the tjm component of MindX-add exists, the vcjob namespace cannot be used.)
data:
  fault-npus: |
    {
        "status":"initializing"
    }
  checkCode: ""
---
apiVersion: mindxdl.gitee.com/v1
kind: AscendJob
metadata:
  name: default-test-mindspore
  labels:
    framework: mindspore
    fault-scheduling: "grace"
    ring-controller.atlas: ascend-910b
spec:
  schedulerName: volcano    # work when enableGangScheduling is true
  runPolicy:
    schedulingPolicy:
      minAvailable: 3       # work when enableGangScheduling is true
      queue: default
  successPolicy: AllWorkers
  replicaSpecs:
    Scheduler:
      replicas: 1  #Scheduler can only be 1
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            ring-controller.atlas: ascend-910b
        spec:
          terminationGracePeriodSeconds: 360
          nodeSelector:                        # modify according to the actual situation
            host-arch: huawei-arm
            accelerator-type: module-910b-16
          containers:
          - name: ascend # do not modify
            image: mindspore-test:latest       # training framework image， which can be modified
            imagePullPolicy: IfNotPresent
            command:                           # training command, which can be modified
              - /bin/bash
              - -c
            args: ["cd /job/code/scripts; chmod +x train_start.sh; bash train_start.sh /job/code/ /job/code/output train.py  --data_path=/job/data/resnet50/imagenet/train --config=/job/code/config/resnet50_imagenet2012_config.yaml"]
            ports:                          # default value containerPort: 2222 name: ascendjob-port if not set
              - containerPort: 2222         # determined by user
                name: ascendjob-port        # do not modify
            volumeMounts:
            - name: code
              mountPath: /job/code
            - name: data
              mountPath: /job/data
            - name: output
              mountPath: /job/output
            - name: ascend-driver
              mountPath: /usr/local/Ascend/driver
            - name: ascend-add-ons
              mountPath: /usr/local/Ascend/add-ons
            - name: dshm
              mountPath: /dev/shm
            - name: localtime
              mountPath: /etc/localtime
          volumes:
          - name: code
            nfs:
              server: 127.0.0.1
              path: "/data/atlas_dls/code/resnet/"
          - name: data
            nfs:
              server: 127.0.0.1
              path: "/data/atlas_dls/public/dataset/"
          - name: output
            nfs:
              server: 127.0.0.1
              path: "/data/atlas_dls/output/"
          - name: ascend-driver
            hostPath:
              path: /usr/local/Ascend/driver
          - name: ascend-add-ons
            hostPath:
              path: /usr/local/Ascend/add-ons
          - name: dshm
            emptyDir:
              medium: Memory
          - name: localtime
            hostPath:
              path: /etc/localtime
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          labels:
            ring-controller.atlas: ascend-910b
        spec:
          terminationGracePeriodSeconds: 360
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: job-name
                        operator: In
                        values:
                          - default-test-mindspore
                      - key: replica-type
                        operator: In
                        values:
                          - worker
                  topologyKey: kubernetes.io/hostname
          nodeSelector:                    # modify according to the actual situation
            host-arch: huawei-arm
            accelerator-type: module-910b-16
          containers:
          - name: ascend # do not modify
            image: mindspore-test:latest   # training framework image， which can be modified
            imagePullPolicy: IfNotPresent
            env:
            # ASCEND_VISIBLE_DEVICES env variable is used by ascend-docker-runtime when in the whole card scheduling scene with volcano scheduler. please delete it when in the static vNPU scheduling scene or without volcano.
            - name: ASCEND_VISIBLE_DEVICES
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['huawei.com/Ascend910']               # The value must be the same as resources.requests
            command:                       # training command, which can be modified
              - /bin/bash
              - -c
            args: ["cd /job/code/scripts; chmod +x train_start.sh; bash train_start.sh /job/code/ /job/code/output train.py  --data_path=/job/data/resnet50/imagenet/train --config=/job/code/config/resnet50_imagenet2012_config.yaml"]
            lifecycle:
              preStop:
                exec:
                  command: [ "/bin/bash", "-c", "cd /job/code/scripts; bash pre_stop.sh" ]
            ports:                          # default value containerPort: 2222 name: ascendjob-port if not set
              - containerPort: 2222         # determined by user
                name: ascendjob-port        # do not modify
            resources:
              limits:
                huawei.com/Ascend910: 4
              requests:
                huawei.com/Ascend910: 4
            volumeMounts:
            - name: fault-config
              mountPath: /user/restore/fault/config
            - name: code
              mountPath: /job/code
            - name: data
              mountPath: /job/data
            - name: output
              mountPath: /job/output
            - name: ascend-driver
              mountPath: /usr/local/Ascend/driver
            - name: ascend-add-ons
              mountPath: /usr/local/Ascend/add-ons
            - name: dshm
              mountPath: /dev/shm
            - name: localtime
              mountPath: /etc/localtime
          volumes:
          - name: fault-config
            configMap:
              name: fault-config-default-test-mindspore                  # Correspond to the ConfigMap name above.
          - name: code
            nfs:
              server: 127.0.0.1
              path: "/data/atlas_dls/code/resnet/"
          - name: data
            nfs:
              server: 127.0.0.1
              path: "/data/atlas_dls/public/dataset/"
          - name: output
            nfs:
              server: 127.0.0.1
              path: "/data/atlas_dls/output/"
          - name: ascend-driver
            hostPath:
              path: /usr/local/Ascend/driver
          - name: ascend-add-ons
            hostPath:
              path: /usr/local/Ascend/add-ons
          - name: dshm
            emptyDir:
              medium: Memory
          - name: localtime
            hostPath:
              path: /etc/localtime