- name: create docker pkg directory
  file:
    path: "{{ docker_pkg_dir }}"
    state: directory
    mode: 0750
  when:
    - inventory_hostname != "localhost"
    - no_copy_flag != "true"

# 压缩docker软件包
- name: archive docker software on localhost
  local_action:
    module: archive
    path: "{{ docker_pkg_dir }}/{{ item }}"
    dest: "{{ docker_pkg_dir }}/{{ item }}.tar.gz"
    mode: 0640
  loop:
    - aarch64
    - x86_64
  when:
    - not (host_count == "1" and first_host == "localhost")
    - no_copy_flag != "true"
  run_once: true

# 复制docker软件包到远端并解压
- name: unarchive docker software on remote
  ansible.builtin.unarchive:
    src: "{{ docker_pkg_dir }}/{{ ansible_architecture }}.tar.gz"
    dest: "{{ docker_pkg_dir }}"
    mode: 0750
    copy: yes
  when:
    - inventory_hostname != "localhost"
    - not (host_count == "1" and first_host == "localhost")
    - no_copy_flag != "true"